services:
  db:
    image: postgres:15-alpine
    container_name: curie-db-dev
    restart: always
    environment:
      POSTGRES_DB: curiedb
      POSTGRES_USER: curieuser
      POSTGRES_PASSWORD: curiepass
    ports:
      - "5433:5432"
    volumes:
      - ./dev-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U curieuser"]
      interval: 5s
      timeout: 3s
      retries: 5
